### ISSUE TITLE
There are some build errors in Win 10?

### ISSUE THREAD

**Issue by timloo0710** [Gigoteur/PX8#59]
Dear all:

After I install MS BUILD TOOLS 2015, 
I ran "cargo build --features="cpython px8_plugin_lua" --release "

It shows message as follows:
   Compiling px8_plugin_lua v0.0.11 (file:///C:/Users/synct/git/PX8/src/plugins/lua)
error: failed to run custom build command for `px8_plugin_lua v0.0.11 (file:///C:/Users/synct/git/PX8/src/plugins/lua)`
process didn't exit successfully: `C:\Users\synct\git\PX8\target\release\build\px8_plugin_lua-d758b5acbc73c5ad\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=static=lua

--- stderr
thread 'main' panicked at 'cl.exe and lib.exe must be on your %PATH% to compile Lua for MSVC.
Please install this crate through the Visual Studio Native Tools Command Line.', src\plugins\lua\build.rs:80
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed

-----------------------------------------
any help?

Best Regards, Tim

**Comment by timloo0710** [comment]
I test the cl.exe, lib.exe in my cmd, 
It shows as follows:

synct@sy-pc MINGW64 ~/git/PX8 (master)
$ cl --v
bash: cl: command not found

synct@sy-pc MINGW64 ~/git/PX8 (master)
$ cl help
bash: cl: command not found

synct@sy-pc MINGW64 ~/git/PX8 (master)
$ cl.exe -v
bash: cl.exe: command not found

synct@sy-pc MINGW64 ~/git/PX8 (master)
$ lib.exe
bash: lib.exe: command not found

-------------------------------------------
Best Regards,Tim

**Comment by timloo0710** [comment]
Hello, All:

I add the  "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" to the "Path"  system variable, 

I alse ran "cargo build --features="cpython px8_plugin_lua" --release", 

It showed  other messages:

   Compiling secur32-sys v0.2.0
   Compiling schannel v0.1.7
error: failed to run custom build command for `px8_plugin_lua v0.0.11 (file:///C:/Users/synct/git/PX8/src/plugins/lua)`
process didn't exit successfully: `C:\Users\synct\git\PX8\target\release\build\px8_plugin_lua-d758b5acbc73c5ad\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=static=lua
lapi.c
lauxlib.c
lbaselib.c
lbitlib.c
lapi.c(13): fatal error C1034: stdarg.h: no include path set

...

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("The command\n\t\"cl.exe\" \"lapi.c\" \"lauxlib.c\" \"lbaselib.c\" \"lbitlib.c\" \"lcode.c\" \"lcorolib.c\" \"lctype.c\" \"ldblib.c\" \"ldebug.c\" \"ldo.c\" \"ldump.c\" \"lfunc.c\" \"lgc.c\" \"linit.c\" \"liolib.c\" \"llex.c\" \"lmathlib.c\" \"lmem.c\" \"loadlib.c\" \"lobject.c\" \"lopcodes.c\" \"loslib.c\" \"lparser.c\" \"lstate.c\" \"lstring.c\" \"lstrlib.c\" \"ltable.c\" \"ltablib.c\" \"ltm.c\" \"lua.c\" \"lundump.c\" \"lutf8lib.c\" \"lvm.c\" \"lzio.c\" \"/c\" \"/MP\" \"/FoC:\\\\Users\\\\synct\\\\git\\\\PX8\\\\target\\\\release\\\\build\\\\px8_plugin_lua-db18ae5e8e449880\\\\out\\\\\" \"/nologo\"\ndid not run successfully.") }) }', src\libcore\result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed

Any help? 

Best Regards

**Comment by hallucino** [comment]
Well it is not so easy to build LUA + Python together. At least I failed until now too. But you can compile separately !

**Comment by hallucino** [comment]
No it is available.
